### ISSUE TITLE
Add support for Telugu

### ISSUE THREAD

**Issue by ChillarAnand** [rohitsaluja22/OpenOCRCorrect#1]

**Comment by rohitsaluja22** [comment]
Hi, Anand, thanks for showing your interest. If you have good understanding of C++, just replace the data from attached code in functions toslp1(string) and toDev(string) in any of Language. The functions are available in slpNPatternDict.h. Else please give us some time to update.

[TeluguSlpFIles.zip](https://github.com/rohitsaluja22/OpenOCRCorrect/files/1332929/TeluguSlpFIles.zip)
