### ISSUE TITLE
Demo video link broken on README

### ISSUE THREAD

**Issue by lokeshh** [rohitsaluja22/OpenOCRCorrect#13]
This link https://tinyurl.com/y7wbpo6m is broken which is mentioned on README

**Comment by gasyoun** [comment]
@rohitsaluja22 fixed?

**Comment by suubh** [comment]
Yes the link is broken . The correct link is : https://www.youtube.com/watch?v=0hcdlF-zn8E .
Should I fix it by raising a PR ? @rohitsaluja22

**Comment by rohitsaluja22** [comment]
fixed, closing it
