### ISSUE TITLE
What is the reason for using Qt?

### ISSUE THREAD

**Issue by VinayNagalgaonkar1998** [rohitsaluja22/OpenOCRCorrect#5]

**Comment by rohitsaluja22** [comment]
Using Qt is not that important, we started with working on tesseract so we had to work in C++. But later we just used text files from OCR engines, so tesseract code is commented at some places. We wanted to show the text boxes (through tesseract) on image while user is correcting text on left editor, but that ended up in great speed loss, so we just commented the text.
