### ISSUE TITLE
How are you getting output from OCR? Can you point out the component from your project related to this?

### ISSUE THREAD

**Issue by VinayNagalgaonkar1998** [rohitsaluja22/OpenOCRCorrect#6]

**Comment by rohitsaluja22** [comment]
We do not use any OCR engine in the backend. We use the text files obtained from tesseract, Google Docs, Indsenz etc.

Output of OCR engine is what is displayed on the text editor side of gui. Refer "IEROCR" and "GEROCR" and page by page output in folder "Inds" in Readme for using 2 OCR engines. These files are available for each sample book I have given in github repo.
