### ISSUE TITLE
What are the error models that you have rectified using this project? Have you implemented any technique like machine learning/deep learning in this project? If yes, could you explain it in short to us?

### ISSUE THREAD

**Issue by VinayNagalgaonkar1998** [rohitsaluja22/OpenOCRCorrect#7]

**Comment by rohitsaluja22** [comment]
Have used ML(for error detections) and Deep learning (for detections and corrections) in my papers here (Refer publications 2-6): https://www.cse.iitb.ac.in/~rohitsaluja/publication.html  The output of OCR engines can be parsed through these models and you can easily load them as different auxiliary sources. This saves time, if you code for using them on the fly, that needs gpu and on cpu it will slow down the process, so better to create sources in starting of document correction and load them page by page.
