### ISSUE TITLE
Doubt in research paper 4 from : https://www.cse.iitb.ac.in/~rohitsaluja/publication.html

### ISSUE THREAD

**Issue by VinayNagalgaonkar1998** [rohitsaluja22/OpenOCRCorrect#9]
How are getting the results in the graph of 'Avg. time per error' v/s 'Page No', like what is step by step procedure for obtaining the mentioned graph.

**Comment by rohitsaluja22** [comment]
1. Users used OpenOCRCorrect to correct the pages manually and they also save the time (as shown in gui) to correct each page.
2. We then find total no. of errors in each page and divide it by time spent on each page.
3. Then these plots are drawn using moving average to make them smooth over page numbers (search for moving average with python/matlab on google).
